### ISSUE TITLE
Consider using hashabler to support hashing arbitrary types?

### ISSUE THREAD

**Issue by jberryman** [christian-marie/xxhash#2]
Would you be interested in merging changes that permitted hashing of arbitrary [`Hashable`](http://hackage.haskell.org/package/hashabler-1.2.1/docs/Data-Hashabler.html#t:Hashable) types from my `hashabler` package? The resulting hash functions would look something like:

```
xxHash :: Hashable a=> a -> XXHash
```

where `a` may also be `ByteString`. This would allow hashing of arbitrary haskell values in a performant way (without needing to marshal to a bytestring first), and cross-platform consistent way, etc.

Let me know if you're interested and would like more details about what that might look like.

**Comment by christian-marie** [comment]
Missed this, sorry.

Certainly would merge such changes, if you'd still like to.
