### ISSUE TITLE
Please support current versions of 'base'

### ISSUE THREAD

**Issue by peti** [christian-marie/xxhash#3]
Is there any particular reason why you builds exclude `base-4.9.0.0`? (http://packdeps.haskellers.com/feed?needle=xxhash) I see no reason why the package shouldn't build with that library, and the current restriction breaks builds with GHC 8.0.x.

**Comment by christian-marie** [comment]
Nope. Bitrot. I'll take a look tomorrow.

**Comment by domenkozar** [comment]
Ping

**Comment by christian-marie** [comment]
So, I don't see *why* anything thinks that this upper bound exists.

On Hackage, the upper bound is 5, as per #1.

That said, I did not release a new version just to loosen the bounds, I simply edited the .cabal file on hackage. I'd prefer not to perform a gratuitous bump to unclog the tubes, but this might be needed?

**Comment by christian-marie** [comment]
I've just made the gratutious bump and tested against stack lts-7.15, ghc 8.01. 9b7eb2ec961344920b8ce9305a3ec6958a328077
